Script started on 2019-04-22 21:23:26+08:00 [TERM="xterm" TTY="/dev/pty0" COLUMNS="80" LINES="24"]
]0;~
[32mtztmw@CHIHCHENG-LAPTOP [33m~[0m
$ whoami; pwd
tztmw
/home/tztmw
]0;~
[32mtztmw@CHIHCHENG-LAPTOP [33m~[0m
$ git config -l
[?1h=user.name=Ting199708[m
user.email=tztmw712861@gmail.com[m
[K[?1l>]0;~
[32mtztmw@CHIHCHENG-LAPTOP [33m~[0m
$ git clone https://github.com/Ting199708/lab1.git
Cloning into 'lab1'...
remote: Enumerating objects: 3, done.[K
remote: Counting objects:  33% (1/3)   [Kremote: Counting objects:  66% (2/3)   [Kremote: Counting objects: 100% (3/3)   [Kremote: Counting objects: 100% (3/3), done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~
[32mtztmw@CHIHCHENG-LAPTOP [33m~[0m
$ exit

Script done on 2019-04-22 21:24:31+08:00 [COMMAND_EXIT_CODE="0"]
